"""empty message

Revision ID: fa84cb56a69c
Revises: f821db16d4f6
Create Date: 2022-01-31 20:44:01.462672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa84cb56a69c'
down_revision = 'f821db16d4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user_id')
    # ### end Alembic commands ###
