"""empty message

Revision ID: f821db16d4f6
Revises: e4a6b463b997
Create Date: 2022-01-30 22:39:07.484942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f821db16d4f6'
down_revision = 'e4a6b463b997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'card_number',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'card_number',
               existing_type=sa.String(length=16),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
