"""empty message

Revision ID: c1c6e1255430
Revises: 3331e7273a85
Create Date: 2022-01-30 21:23:44.894221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c6e1255430'
down_revision = '3331e7273a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_user_id_fkey', 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('addresses_user_id_fkey', 'addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
